In [4]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [7]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
a.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [33]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
a.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)

In [22]:
a = np.array([1,2,3,4,5], ndmin = 5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [27]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
a[0][2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


3

In [24]:
a[0]

array([1, 2, 3, 4, 5])

In [25]:
a[0:1]

array([[1, 2, 3, 4, 5]])

In [26]:
a[0][1]

2

In [28]:
# slicing
a[0][:1]

array([1])

In [29]:
a.dtype

dtype('int32')

In [34]:
# reshaping array
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b.shape

(12,)

In [38]:
c = b.reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
c = b.reshape(6,2)

In [42]:
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
# reshaping into 3D array
c = b.reshape(2,3,2)

In [44]:
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [74]:
d = b.reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
d = b.reshape(-1)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
# Numpy.random function for float
np.random.rand()

0.4210622028715014

In [56]:
# Numpy.random function for Integer
np.random.randint(100)

68

In [55]:
np.random.randint(100,size = 5)


array([29, 50, 34, 13,  1])

In [58]:
# 2D array for float
np.random.rand(4,5)

array([[0.11679779, 0.40120681, 0.14944753, 0.62114778, 0.38096556],
       [0.20252739, 0.87089419, 0.09350757, 0.44619415, 0.44339404],
       [0.9402946 , 0.42962979, 0.05128594, 0.79675348, 0.92776362],
       [0.26273908, 0.68091526, 0.96189435, 0.17742848, 0.46828418]])

In [59]:
# 3D array for float
np.random.rand(3,4,5)

array([[[0.43961282, 0.45118796, 0.49269239, 0.11433437, 0.07079424],
        [0.31127939, 0.48174263, 0.58849069, 0.45501597, 0.20906591],
        [0.19687006, 0.36033098, 0.23189521, 0.63534056, 0.1496782 ],
        [0.83973604, 0.26431636, 0.2868256 , 0.53426651, 0.33018969]],

       [[0.79424332, 0.00646174, 0.88171161, 0.17614867, 0.48298556],
        [0.16720863, 0.23173183, 0.89373209, 0.68152506, 0.18651372],
        [0.5448631 , 0.53810916, 0.04351625, 0.07023164, 0.61426767],
        [0.19325353, 0.96823697, 0.38703501, 0.25457202, 0.42773239]],

       [[0.66081835, 0.23291481, 0.51552419, 0.46771012, 0.39584924],
        [0.92957411, 0.52617187, 0.33443572, 0.23921714, 0.63468356],
        [0.5645377 , 0.00157879, 0.15837204, 0.84948648, 0.96415839],
        [0.03896554, 0.74777314, 0.03428897, 0.26008343, 0.66803586]]])

In [61]:
# Binomial/ Normal Distribution
np.random.binomial(n =10, p =0.5, size =1)

array([6])

In [63]:
np.random.binomial(n =2, p =0.5, size =10)

array([1, 0, 1, 2, 1, 1, 2, 1, 2, 1])

In [64]:
# Normal Distribution
np.random.normal(loc =2, scale =4, size=10)

array([ 5.10275236, -3.70759661, -0.90246388, -2.69753426,  4.68962262,
        0.32084071,  4.27128677, -2.1585601 ,  2.78005399, 11.6987298 ])

In [67]:
# mean of the distribution
np.mean(np.random.normal(loc =2, scale =4, size=10))

1.2426275224072936

In [69]:
c.shape

(3, 4, 1)

In [70]:
c

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [76]:
d*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])